# Translations template for PROJECT.
# Copyright (C) 2025 ORGANIZATION
# This file is distributed under the same license as the PROJECT project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2025.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PROJECT VERSION\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2025-03-31 15:51-0500\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.17.0\n"

#: main.py:40
msgid "welcome_message"
msgstr ""

#: alembic/env.py:27
msgid "error_database_url_missing"
msgstr ""

#: apps/chat/routes.py:27
msgid "error_sql_processing_failed"
msgstr ""

#: apps/chat/routes.py:34
msgid "error_server_busy"
msgstr ""

#: apps/dashboard/routes.py:21
msgid "error_schema"
msgstr ""

#: apps/dashboard/routes.py:33
msgid "error_analysis"
msgstr ""

#: apps/file_manager/routes.py:24 apps/file_manager/routes.py:40
msgid "file_saved_message"
msgstr ""

#: apps/synthetic_data/routes.py:13
msgid "table_name_description"
msgstr ""

#: apps/synthetic_data/routes.py:16
msgid "num_records_description"
msgstr ""

#: apps/synthetic_data/routes.py:19
msgid "details_description"
msgstr ""

#: apps/synthetic_data/service.py:20
msgid "table_not_found"
msgstr ""

#: apps/synthetic_data/service.py:24
msgid "error_details_too_long"
msgstr ""

#: utils/db_manager.py:61
msgid "error_no_csv_xlsx_found"
msgstr ""

#: utils/db_manager.py:71
msgid "error_unsupported_file_format"
msgstr ""

#: utils/env_manager.py:14
msgid "error_openai_api_key_missing"
msgstr ""

